---
name: §6Better§dSitting§f
author: [Niko]
version: "1.1-TESTER-VERSION"
api:
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
main: BetterSitting\BetterSitting

commands:
  bettersit:
    description: BetterSitting main command
    aliases: [bsit]

permissions:
  bettersit.op:
    description: "OP permission, allow OPs to use OP Commands."
    default: op
    childen:
      bettersit.op.sitonspecialblocks:
         description: "Allows OPs to sit on special blocks."
         default: op
---
