---
name: §6Better§dSitting§f
author: [Niko]
version: "1.1-TESTER-VERSION"
api:
- 1.0.0
- 1.1.0
- 1.2.0
- 1.3.0
- 1.4.0
- 1.5.0
- 1.13.0
- 1.14.0
- 2.0.0
- 2.1.0
- 2.14.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA5
- 4.0.0
main: BetterSitting\BetterSitting

commands:
  bettersit:
    description: BetterSitting main command
    aliases: [bsit]

permissions:
  bettersit.op:
    description: "OP permission, allow OPs to use OP Commands."
    default: op
    childen:
      bettersit.op.sitonspecialblocks:
         description: "Allows OPs to sit on special blocks."
         default: op
---